# Day 10

In [1]:
# difference between linear regression and logistic regression
# decision tree
# random forest

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
wine = pd.read_csv('/Users/Ganesh/Desktop/SFJ/Data/Wine.csv')
wine.head()

Alcohol  Malic_Acid  Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0       13           2    6            13        125              1   
1       11           6    4            10        147              3   
2       11           4    3            13         89              2   
3       15           6    6            11        151              4   
4       12           2    3            13        146              0   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  Hue  \
0           0                  0.71                3                8    1   
1           2                  0.66                4                2    2   
2           4                  0.36                2                3    1   
3           4                  0.54                5               11    1   
4           1                  0.35                2                7    1   

   OD280  Proline  Customer_Segment  
0      1     1004                 1  
1      1      681                 1  
2      3      946                 1  
3      3      319                 1  
4      3     1640                 1

In [66]:
features = wine.values[:, :13]  # X
target = wine.values[:, 13] # y
train_X, test_X, train_y, test_y = train_test_split(features, target, test_size=0.2, random_state=0)

In [67]:
lr = LogisticRegression()
lr.fit(train_X, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [68]:
y_pred = lr.predict(test_X)

In [69]:
train_X.shape

(142, 13)

In [70]:
test_X.shape

(36, 13)

In [71]:
y_pred

array([2., 3., 3., 3., 2., 1., 2., 2., 2., 2., 3., 3., 2., 2., 2., 2., 3.,
       1., 2., 1., 3., 1., 2., 3., 1., 2., 2., 3., 2., 2., 2., 3., 2., 2.,
       2., 2.])

In [76]:
accuracy_score(test_y, y_pred)

0.4444444444444444

In [77]:
len(test_y)

36

In [74]:
confusion_matrix(test_y, y_pred)

array([[ 3,  8,  3],
       [ 2, 10,  4],
       [ 0,  3,  3]])

In [78]:
# Correct 16
# wrong 20
16/36

0.4444444444444444

In [79]:
dt = DecisionTreeClassifier()
dt.fit(train_X, train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [80]:
dt_pred = dt.predict(test_X)

In [81]:
accuracy_score(test_y, dt_pred)

0.3611111111111111

In [82]:
confusion_matrix(test_y, dt_pred)

array([[6, 3, 5],
       [3, 7, 6],
       [2, 4, 0]])

In [ ]:
# Random Forest --- Collection of trees
# iris dataset
# handwritten digit detection

In [246]:
from sklearn.ensemble import RandomForestClassifier
# from sklearn.datasets import load_boston
from sklearn.datasets import load_iris

In [247]:
iris = load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [248]:
type(iris.data)

numpy.ndarray

In [249]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [250]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [251]:
len(df)

150

In [252]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [253]:
# df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [254]:
# df.head()

In [255]:
len(df)

150

In [256]:
# HOMEWORK

# goal -- To predict the species of the flowers by using Machine Learning with Python. (Use iris dataset)
# X
# y
# train_X, test_X, train_y, test_y = train_test_split(features, target, test_size=0.3, random_state=5)
# rf_model = RandomForestClassifier()
# also try the same using LogisticRegression()
# confusion_matrix, accuracy for both algorithms

In [257]:
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

In [258]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [259]:
# train_test_split()
df['is_train'] = np.random.uniform(0,1,len(df)) <= 0.6

In [260]:
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True  
5  setosa      True  
6  setosa     False  
7  setosa     False  
8  setosa      True  
9  setosa     False

In [261]:
len(df[df['is_train'] == False])
# sns.countplot(df.is_train)

32

In [262]:
train = df[df['is_train'] == True]
test = df[df['is_train'] == False]

In [263]:
len(train)

118

In [264]:
len(test)

32

In [265]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [266]:
features = df.columns[:4]

In [267]:
train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [268]:
len(test)

32

In [269]:
train.species.unique()

[setosa, versicolor, virginica]
Categories (3, object): [setosa, versicolor, virginica]

In [270]:
# train['species'] = train['species'].map({'setosa': 0, 'versicolor':1, 'virginica': 2})

# OR
train.species = pd.Categorical(train.species)
train.species = train.species.cat.codes

# OR
# train.apply(func)

/Users/Ganesh/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3643: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [271]:
train.species.unique()

array([0, 1, 2])

In [272]:
train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  is_train  
0        0      True  
1        0      True  
2        0      True  
3        0      True  
4        0      True

In [273]:
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [274]:
y = train['species']

In [275]:
rf_model = RandomForestClassifier(n_estimators=10, random_state=2)
rf_model.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [276]:
rf_model.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int8)

In [277]:
preds = iris.target_names[rf_model.predict(test[features])]

In [278]:
preds

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica'], dtype='<U10')

In [279]:
test['species'][:5]

6     setosa
7     setosa
9     setosa
13    setosa
15    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [280]:
len(test)

32

In [281]:
pd.crosstab(test['species'], preds, rownames=['Actual Species'], colnames=['Predited Species'])

Predited Species  setosa  versicolor  virginica
Actual Species                                 
setosa                14           0          0
versicolor             0          13          0
virginica              0           0          5

In [282]:
# 1+3 = 4 ---> incorrect predictions
# 11+7+12 = 30 --> Correct predictions
# Model accuracy
accuracy = (30/34) * 100
# accuracy --> 88.23529411764706

In [283]:
accuracy_score(test['species'], preds) * 100

100.0